---
name: astrodb
"@id": "#astrodb_template"
description: "Template database for use by the AstroDB Toolkit"

tables:
  - name: Publications
    "@id": "#Publications"
    description: Reference information (DOI, bibcodes, etc)
    primaryKey: 
    - "#Publications.reference"

    columns:
    - name: reference
      "@id": "#Publications.reference"
      datatype: string
      length: 30
      description: Publication reference identifier
      ivoa:ucd: meta.id;meta.main
    - name: bibcode
      "@id": "#Publications.bibcode"
      datatype: string
      length: 100
      description: Publication bibcode
    - name: doi
      "@id": "#Publications.doi"
      datatype: string
      length: 100
      description: Publication DOI
    - name: description
      "@id": "#Publications.description"
      datatype: string
      length: 1000
      description: Publication description


  - name: Sources
    "@id": "#Sources"
    description: "Main identifiers for objects along with coordinates."
    primaryKey:
    - "#Sources.source"

    columns:
    - name: source
      "@id": "#Sources.source"
      datatype: string
      length: 100
      description: Unique identfier for an object
      ivoa:ucd: meta.id;src;meta.main
      nullable: false
    - name: ra_deg
      "@id": "#Sources.ra_deg"
      datatype: double
      description: ICRS Right Ascension of object
      fits:tunit: deg
      ivoa:ucd: pos.eq.ra;meta.main
    - name: dec_deg
      "@id": "#Sources.dec_deg"
      datatype: double
      description: ICRS Declination of object
      fits:tunit: deg
      ivoa:ucd: pos.eq.dec;meta.main
    - name: reference
      "@id": "#Sources.reference"
      datatype: string
      length: 30
      description: Publication reference; links to Publications table
      nullable: false

    indexes:
      - name: PK_Sources_source
        "@id": "#PK_Sources_source"
        description: Primary key for Sources table
        columns: 
        - "#Sources.source"
    constraints:
      - name: check_ra
        "@type": Check
        "@id": "#Sources_check_ra_bounds"
        description: Validate RA range
        expression: ra_deg >= 0 AND ra_deg <= 360
      - name: Source_reference_Publications_reference
        "@type": "ForeignKey"
        "@id": "#FK_Sources_reference_Publications_reference"
        description: Link Source reference to Publications table
        columns:
        - "#Sources.reference"
        referencedColumns:
        - "#Publications.reference"
        

