---
name: astrodb
"@id": "#astrodb_template"
description: "Template database for use by the AstroDB Toolkit"
tables:
  - name: Sources
    "@id": "#Sources"
    description: "Main identifiers for objects along with coordinates."
    columns:
    - name: source
      "@id": "#Sources.source"
      datatype: string
      length: 100
      description: Unique identfier for an object
      ivoa:ucd: meta.id;src;meta.main
    - name: ra_deg
      "@id": "#Sources.ra_deg"
      datatype: double
      description: ICRS Right Ascension of object
      fits:tunit: deg
      ivoa:ucd: pos.eq.ra;meta.main
    indexes:
      - name: PK_Sources_source
        "@id": "#PK_Sources_source"
        description: Primary key for Sources table
        columns: 
        - "#Sources.source"
    constraints:
      - name: check_ra
        "@type": Check
        "@id": "#Sources_check_ra_bounds"
        description: Validate RA range
        expression: ra_deg >= 0 & ra_deg <= 360
        

