# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Scheduled tests

on:
  schedule:
    - cron: '30 1 1 * *' # runs on the first day of the month at 1:30 UTC
  workflow_dispatch:  # manual execution

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install astrodbkit
        pip install lsst-felis
        pip install pytest pytest-cov
    - name: Test with pytest
      run: |
        pytest --cov=schema -s -rpP tests/scheduled_checks.py
